language: java

# Testo su diverse jdk
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "danilo-dellorco"
    token: "9a5ef57a05a6d70a5cfd08fe8e2c48abe7d66c41"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danilo-dellorco_deliverable1